name: osx

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit, branch or tag to build'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: macos-13
            arch: x86_64
          - runs-on: macos-14
            arch: arm64
          - runs-on: macos-15
            arch: arm64
    runs-on: ${{ matrix.runs-on }}
    env:
      ARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      with:
        ref: ${{ github.event.inputs.ref }}
        persist-credentials: false

    - name: Checkout sample streams
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      with:
        repository: strukturag/libde265-data
        path: libde265-data
        persist-credentials: false

    - name: Install dependencies
      run: |
        ./scripts/ci-before-install-osx.sh

    - name: Prepare CI
      run: |
        ./scripts/ci-before-script.sh

    - name: Run tests
      run: |
        ./scripts/ci-run.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.arch }}
        path: |
          build/dec265/dec265
          build/libde265/libde265.dylib
          build/libde265/libde265.dylib.*
        retention-days: 30
        if-no-files-found: warn
